### ISSUE TITLE
Debug output of `Vec` shows tuple entries rather than `T`

### ISSUE THREAD

**Issue by chanced** [ibraheemdev/boxcar#11]
Currently, the implementation of `fmt::Debug` is displaying the entries as tuples of `(index, value)`.

e.g.:
```rust
use std::fmt::Write as _;
let mut buf = String::new();
let v = vec![1, 2, 3];
write!(&mut buf, "{v:?}");
asssert_eq!(buf, "[1, 2, 3]");
```
```
assertion `left == right` failed
  left: "[(0, 1), (1, 2), (2, 3)]"
 right: "[1, 2, 3]"
```

**Comment by clarfonthey** [comment]
I believe that the reason for this is because the indices in the `Vec` can have gaps, due to things having been not-yet pushed. Although you could probably just show a placeholder for those entries as (`_`) instead of just showing the indices for all of them.

**Comment by chanced** [comment]
Ah, gotcha. I should have known that was intentional :)

Sorry about that. I'll close the ticket and the PR.

**Comment by ibraheemdev** [comment]
I don't think this was intentional, the `Debug` implementation changed when `Iter` was changed a while back to return indices. I think I would prefer `Debug` to match `Vec` — it's more readable, and `Debug` output is a lot less of a footgun than the iterator output.
