### ISSUE TITLE
Would it be possible for `Vec<T>` to have a `push_with` method?

### ISSUE THREAD

**Issue by chanced** [ibraheemdev/boxcar#9]
Basically I'm curious if it would be possible to have a method with the signature:
```rust
fn push_with<F: FnOnce(usize) -> T>(&self, f:F) -> usize;
```
where `usize` is the index for which the record will be inserted at?

The inspiration for this question is for situations where the index needs to be added to the record going into the vec.

**Comment by ibraheemdev** [comment]
I would accept a PR implementing this!

**Comment by chanced** [comment]
Rock on! I'll try and work on it this week or weekend.
